/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class neu_dreamerajni_utils_OpenCVSmooth */

#ifndef _Included_neu_dreamerajni_utils_OpenCVSmooth
#define _Included_neu_dreamerajni_utils_OpenCVSmooth
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     neu_dreamerajni_utils_OpenCVSmooth
 * Method:    smooth
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_neu_dreamerajni_utils_OpenCVSmooth_smooth
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
