/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class neu_dreamerajni_utils_OpenCVHelper */

#ifndef _Included_neu_dreamerajni_utils_OpenCVHelper
#define _Included_neu_dreamerajni_utils_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     neu_dreamerajni_utils_OpenCVHelper
 * Method:    Canny
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_neu_dreamerajni_utils_OpenCVHelper_Canny
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
