/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class neu_dreamerajni_utils_OpenCVCanny */

#ifndef _Included_neu_dreamerajni_utils_OpenCVCanny
#define _Included_neu_dreamerajni_utils_OpenCVCanny
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     neu_dreamerajni_utils_OpenCVCanny
 * Method:    canny
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_neu_dreamerajni_utils_OpenCVCanny_canny
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
